id: A890DFA86
base_file: f49B9.txt
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-30 21:35:23.201302
  last_modified_at: 2022-05-30 21:35:23.201305
