id: A890DFA86
base_file: f439A.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 21:35:23.185246
  last_modified_at: 2022-05-30 21:35:23.185249
