id: A890DFA86
base_file: f4E60.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 21:35:23.243157
  last_modified_at: 2022-05-30 21:35:23.243164
