id: A890DFA86
base_file: f0061.txt
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-05-30 21:35:23.106948
  last_modified_at: 2022-05-30 21:35:23.106956
