id: A890DFA86
base_file: f6616.txt
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-05-30 21:35:23.272428
  last_modified_at: 2022-05-30 21:35:23.272431
