id: A890DFA86
base_file: fF2E2.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 21:35:23.454996
  last_modified_at: 2022-05-30 21:35:23.454999
