id: A890DFA86
base_file: f2450.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-05-30 21:35:23.139474
  last_modified_at: 2022-05-30 21:35:23.139477
