id: A890DFA86
base_file: f0768.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-30 21:35:23.116700
  last_modified_at: 2022-05-30 21:35:23.116703
