id: A890DFA86
base_file: f24FB.txt
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-05-30 21:35:23.140872
  last_modified_at: 2022-05-30 21:35:23.140875
