id: A890DFA86
base_file: fA42A.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 21:35:23.349760
  last_modified_at: 2022-05-30 21:35:23.349763
