id: A890DFA86
base_file: f7A57.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - bo
  datatype: PlainText
  created_at: 2022-05-30 21:35:23.296556
  last_modified_at: 2022-05-30 21:35:23.296558
