id: A890DFA86
base_file: f4D30.txt
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-30 21:35:23.211596
  last_modified_at: 2022-05-30 21:35:23.211599
