id: A890DFA86
base_file: f4A46.txt
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-05-30 21:35:23.205201
  last_modified_at: 2022-05-30 21:35:23.205204
