id: A890DFA86
base_file: f4C2A.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 21:35:23.206647
  last_modified_at: 2022-05-30 21:35:23.206650
