id: A890DFA86
base_file: fEAF7.txt
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-30 21:35:23.441940
  last_modified_at: 2022-05-30 21:35:23.441943
