id: A890DFA86
base_file: f0EEB.txt
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-05-30 21:35:23.126288
  last_modified_at: 2022-05-30 21:35:23.126293
